baseurl = "http://english.etcbc.org/"
languageCode = "en-us"
title = "East Toronto Chinese Baptist Church"
theme = "hugo-creative-theme"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "East Toronto Chinese Baptist Church"
	description = "A multi-congregation church within Toronto's Victoria Village"

	# The path must be relative to the static folder
	favicon = "favicon.ico"

        twitter = "etcbc_tweets"
#### Things below this line are for the theme ####
	# Navigation
	[params.navigation]
        brand = "East Toronto Chinese Baptist Church"

        [params.navigation.links]
            about     = "About"
            services  = "Service"
            leadership = "Leadership"
            ministries = "Ministries"
            blog = "Blog"
            contact   = "Contact"

	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Is this a warehouse?"
		subtitle   = "It may appear to be one right now... but over the past few years, we've fundraised and have begun major renovations!"
		buttonText = "Find out more about our Nehemiah Project!"


	# About section
	[params.about]
		headline    = "Situated in Victoria Village"
		description = "We are a [CBOQ](//baptist.ca) church situated in Toronto, Ontario.  With a healthy 300 person multi-congregational something, we focus on becoming an integrated part of our local community... to be ushers in bringing God's glory here on Earth"
		buttonText  = "What's our history?"


	# Service section
	[params.services]
		headline = "Our service times"

        [[params.services.list]]
            icon = "fa-book"
            title = "English Service"
            description = "We currently meet at 11:30am in the main Sanctuary every Sunday!"

        [[params.services.list]]
            icon = "fa-home"
            title = "Cantonese Service"
            description = "We currently meet at 10am in the main Sanctuary every Sunday with the Mandarin congregation!"

	[[params.services.list]]
            icon = "fa-heart"
            title = "Mandarin Service"
            description = "We currently meet at 10am in the main Sanctuary every Sunday with the Cantonese congregation!"

    # Portfolio modals
	[params.portfolio.modal]
        client = "Contact"
        buttonText = "Close"
        date = "Last Updated"

    # Aside section
	[params.aside]
        headline = "Looking for this week's bulletin?"

        [params.aside.button]
        text = "Download now"
        link = "//this.is.a.false.link.c2om"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
		phone = "123-456-6789"
		email = "feedback@startbootstrap.com"
